services:
  point-virgule:
    build: .
    container_name: point-virgule
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./recordings:/app/recordings
    networks:
      - point-virgule

  point:
    image: ghcr.io/clubcedille/point:latest
    container_name: point
    ports:
      - "5000:5000"
    networks:
      - point-virgule

  # virgule:
  #   build: ../virgule
  #   container_name: virgule
  #   ports:
  #     - "5001:5001"
  #   networks:
  #     - point-virgule
  #   volumes:
  #     - .:/app

networks:
  point-virgule:
    driver: bridge